# name your datacenter
global:
  name: consul
  datacenter: dc1
server:
  replicas: 1
ui:
  enabled: true
connectInject:
  transparentProxy:
    defaultEnabled: false
  # inject an envoy sidecar into every new pod, except for those with annotations that prevent injection
  enabled: true
  # these settings enable L7 metrics collection and are new in 1.5
  centralConfig:
    enabled: true
    # proxyDefaults is a raw json string that will be applied to all Connect
    # proxy sidecar pods that can include any valid configuration for the
    # configured proxy.
    # proxyDefaults: |
    #   {
    #     "envoy_prometheus_bind_addr": "0.0.0.0:9102"
    #   }
controller:
  enabled: true